# Form implementation generated from reading ui file 'UI/add_edit_coffee_form.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(561, 356)
        self.sortNameLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.sortNameLineEdit.setGeometry(QtCore.QRect(150, 90, 113, 20))
        self.sortNameLineEdit.setObjectName("sortNameLineEdit")
        self.priceLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.priceLineEdit.setGeometry(QtCore.QRect(150, 210, 113, 20))
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.volumeLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.volumeLineEdit.setGeometry(QtCore.QRect(150, 250, 113, 20))
        self.volumeLineEdit.setObjectName("volumeLineEdit")
        self.groundBeansLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.groundBeansLineEdit.setGeometry(QtCore.QRect(150, 170, 113, 20))
        self.groundBeansLineEdit.setObjectName("groundBeansLineEdit")
        self.roastDegreeLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.roastDegreeLineEdit.setGeometry(QtCore.QRect(150, 130, 113, 20))
        self.roastDegreeLineEdit.setObjectName("roastDegreeLineEdit")
        self.tasteDescriptionTextEdit = QtWidgets.QTextEdit(parent=Form)
        self.tasteDescriptionTextEdit.setGeometry(QtCore.QRect(290, 90, 104, 71))
        self.tasteDescriptionTextEdit.setObjectName("tasteDescriptionTextEdit")
        self.saveButton = QtWidgets.QPushButton(parent=Form)
        self.saveButton.setGeometry(QtCore.QRect(310, 220, 75, 23))
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveButton.setText(_translate("Form", "Save"))